language: python
python:
    - 3.3
    - 3.4

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then travis_retry pip install asyncio pathlib; fi

script:
    - nosetests --with-coverage --cover-erase --cover-package=aioftp
