language: python
python:
    - 3.5

install:
    - travis_retry pip install coveralls flake8

before_script:
    - flake8 aioftp

script:
    - python setup.py test

branches:
    only:
        - master

after_success:
    coveralls
