language: python
python:
    - 3.4
    - 3.5

install:
    - travis_retry pip install coveralls

script:
    - python setup.py test

branches:
    only:
        - master

after_success:
    coveralls
